- hosts: 
        - developement
  remote_user: root
  tasks:
    - name: Install some dependencies
      apt:
              pkg:
                      - python3
                      - vim
                      - tmux
                      - gdb
                      - valgrind
                      - git
                      - fish
                      - curl
                      - unzip
                      - tar
                      - snapd
                      - g++
                      - gcc
                        
    - name: Install cmake
      snap:
              name: cmake
              classic: yes

    - name: Set shell
      command: chsh -s /usr/bin/fish
        
    - name: Create config folder for fish
      file:
              path: /root/.config/fish
              state: directory

    - name: Copy shell config
      copy:
              src: ./config.fish
              dest: /root/.config/fish/config.fish
              owner: root
              group: root
              mode: '0777'

   
    - name: Clone vcpkg
      git:
              repo: https://github.com/microsoft/vcpkg.git
              dest: /root/vcpkg

    - name: Install vcpkg
      command: bash /root/vcpkg/bootstrap-vcpkg.sh
