- hosts: developement
  tasks:
          - name: Set authorized keys
            authorized_key:
                    user: root
                    state: present
                    key: "{{ lookup('file', lookup('env','HOME') + '/.ssh/id_ed25519.pub') }}" 
