format_version: 3
pipelines:
  test_dev_environment:
    group: My-Pipelines
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    materials:
      git:
        git: https://github.com/Hnatekmar/dev_environment.git
        shallow_clone: false
        auto_update: true
        branch: master
    stages:
    - test:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
          allow_only_on_success: false
        jobs:
          ansible_playbook:
            timeout: 0
            tasks:
            - exec:
                arguments:
                - '[developement]'
                - '>>'
                - hosts
                command: echo
                run_if: passed
            - exec:
                arguments:
                - localhost
                - '>>'
                - hosts
                command: echo
                run_if: passed
            - exec:
                arguments:
                - -i
                - hosts
                - dev_environment.yml
                command: ansible-playbook
                run_if: passed
